from .embedbase import EmbedBasedSubstitute
from .counter_fit import CounterFittedSubstitute
from .dces import DCESSubstitute
from .eces import ECESSubstitute
from .hownet import HowNetSubstitute
from .wordnet import WordNetSubstitute
from .glove import GloveSubstitute
from .word2vec import Word2VecSubstitute
from .chinese_sim_char import ChineseSimCharSubstitute
from .chinese_fyh_char import ChineseFYHCharSubstitute
from .chinese_hownet import ChineseHowNetSubstitute
from .chinese_wordnet import ChineseWordNetSubstitute
from .chinese_word2vec import ChineseWord2VecSubstitute
